<?php
/**
 * @file
 * Custom module for this site.
 */

include_once 'rose_contact.form.inc';
include_once 'rose_contact.contact.inc';
include_once 'rose_contact.blocks.inc';

/**
 * Implements hook_mail().
 */
function rose_contact_mail($key, &$message, $params) {
  switch ($key) {
    case 'contact_form':
      $message['subject'] = t('Contact form submission');
      $message['body'][] = $params['body'];
      break;
  }
}
