<?php
/**
 * @file
 * Custom module for this site.
 */

/**
 * Implements hook_init().
 */
function rose_init() {

  // Load the includes for the module
  module_load_include('inc', 'rose', 'rose.form');
  module_load_include('inc', 'rose', 'rose.blocks');
  module_load_include('inc', 'rose', 'rose.contact');

}


/**
 * Implements hook_preprocess_page().
 */
function rose_preprocess_page(&$vars) {
  //drupal_add_css('http://fonts.googleapis.com/css?family=Pontano+Sans|Karla', array('group' => CSS_THEME, 'weight' => 115, 'preprocess' => FALSE));
  drupal_add_js('sites/all/themes/rosenichols/js/jquery.autosize.min.js', 'file');
  drupal_add_js('sites/all/themes/rosenichols/js/custom.js', 'file');
  // drupal_add_css('sites/all/themes/rosenichols/css/ie/lteie8.css', array('group' => CSS_THEME, 'weight' => 115, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  // drupal_add_css('sites/all/themes/rosenichols/css/ie/ie7.css', array('group' => CSS_THEME, 'weight' => 115, 'browsers' => array('IE' => 'IE 7', '!IE' => FALSE), 'preprocess' => FALSE));
}


function rose_preprocess_node(&$vars) {

  if ($vars['type'] == 'post') {

    if (!empty($vars['field_post_portrait_img'])) {
      $vars['classes_array'][] = 'portrait-img';
    }

    if ($vars['view_mode'] == 'full') {
      $vars['classes_array'][] = 'node-full';
    }
  }
}

/**
 * Implements hook_menu().
 */
function rose_menu() {
  $items = array();

  $items['contact'] = array(
    'title' => 'Contact',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rose_message_form'),
    'access callback' => TRUE,
    'file' => 'rose.contact.inc',
    'type' => MENU_CALLBACK
  );

  return $items;
}


/**
 * Implements hook_mail().
 */
function rose_mail($key, &$message, $params) {
  switch ($key) {
    case 'contact_form':
      $message['subject'] = t('Contact form submission');
      $message['body'][] = $params['body'];
      break;
  }
}