; This file was auto-generated by drush make
core = 7.x
api = 2

; Modules
projects[views_bulk_operations][subdir] = "contrib"

projects[admin_menu][subdir] = "contrib"

projects[admin_views][subdir] = "contrib"

projects[backup_migrate][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[module_filter][subdir] = "contrib"

projects[views][subdir] = "contrib"

; Themes
projects[zen][version] = "5.5"
